name: Check Languages Files
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-files:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # v1
      - uses: GuillaumeFalourd/diff-action@b341507d1da990caceac1b3b31b8f55eebaa2e99
        with:
          first_file_path: resources/languages.yml
          second_file_path: go/pkg/utils/langfiles/resources/languages.yml
          expected_result: PASSED
        # v1
      - uses: GuillaumeFalourd/diff-action@b341507d1da990caceac1b3b31b8f55eebaa2e99
        with:
          first_file_path: resources/languages-customization.yml
          second_file_path: go/pkg/utils/langfiles/resources/languages-customization.yml
          expected_result: PASSED
